// Generated by scripts/build-slide-previews.cjs. Original snapshots are preserved.
window.moodysSlides = [
  {
    "title": "Internship final presentation",
    "summary": "A look back at my software engineering internship on the Multimedia and Graphics team.",
    "image": "imgs/moodys/slide-01.webp",
    "source": "moodys-intern-slides/moodys-slide-1.html",
    "transcript": "Jenny's Internship Final Presentation\n\nA quick look into what I learned and accomplished as a software engineering intern on the Multimedia and Graphics team!\n\nPublished 2026\n\nLearn more"
  },
  {
    "title": "A little about me",
    "summary": "My background at UC San Diego, where I am from, and a few interests outside work.",
    "image": "imgs/moodys/slide-02.webp",
    "source": "moodys-intern-slides/moodys-slide-8.html",
    "transcript": "A little about me!\n\nI am a rising senior at the University of California San Diego (UCSD) majoring in Data Science with a minor in Economics.\n\nI'm originally from Warren, New Jersey, and have always dreamed of working in NYC.\n\nI enjoy traveling, hiking, playing videogames, giving unserious food reviews, and filming a random vlog here and there."
  },
  {
    "title": "My internship in numbers",
    "summary": "A visual snapshot of the summer: tickets, coffee chats, training, and more.",
    "image": "imgs/moodys/slide-03.webp",
    "source": "moodys-intern-slides/moodys-slide-7.html",
    "transcript": "My internship in numbers\n\nOver the course of my internship here at Moody's, I've worked on a variety of projects and met a lot of great people.\n\nIn true data visualization fashion, here's a little bar chart to go along with some fun statistics --->\n\nSome fun statistics:\n\n0\n5\n10\n15\n20\nWeeks at Moody's\nTickets Completed\nCoffee Chats\nHours of Training\nCoffee Machine Times Used"
  },
  {
    "title": "Behind the tickets",
    "summary": "Where the tickets took me this summer! (I don't know why the formatting is off on this slide.)",
    "image": "imgs/moodys/slide-04.webp",
    "source": "moodys-intern-slides/moodys-slide-6.html",
    "transcript": "Behind the tickets\n\n• Addressed security vulnerabilities\n\n• Expanded test coverage for existing code\n\n• Updated outdated code to fit newer framework versions\n\n• Created custom visualization components\n\nOn the right is an example of the donut chart component I was working on!\n\nExample of Donut Chart Component:\n\nCartis\n\nFlipbook Development\n\nStoryboard Development\n\nOther\n\n13%\n27%\n33%\n27%"
  },
  {
    "title": "Projects I helped deliver",
    "summary": "Reusable components, Cartis, and the June 2026 Monthly Defaults Flipbook.",
    "image": "imgs/moodys/slide-05.webp",
    "source": "moodys-intern-slides/moodys-slide-5.html",
    "transcript": "Projects I helped deliver\n\nCustom Components: Built reusable components that made recurring flipbooks faster to create and reduced manual work.\n\nCartis: Worked on a tool that lets analysts upload data and create their own charts.\n\nJune 2026 Monthly Defaults Flipbook: Worked with writer Ruth to produce and publish the June Monthly Defaults Flipbook.\n\nThe Flipbook I helped produce!"
  },
  {
    "title": "A chance to help another team",
    "summary": "A Python tools showcase for the Business Intelligence team.",
    "image": "imgs/moodys/slide-06.webp",
    "source": "moodys-intern-slides/moodys-slide-4.html",
    "transcript": "A chance to help another team\n\nHad a chance to work on a Python Showcase for the Business Intelligence team!\n\nA simple showcase demontrating basic tools and libraries that could help with statistics, data visualization, etc.\n\nWas fun to work on and interesting to consider my presentation from both sides as the presenter and audience.\n\nPython tools and libraries in my showcase\n\npandas\n\nData wrangling & analysis\n\nNumPy\n\nFast numerical computing\n\nMatplotlib\n\nFoundational plotting\n\nseaborn\n\nStatistical visualization\n\nSciPy\n\nScientific & stats toolkit\n\nPlotly\n\nInteractive charts"
  },
  {
    "title": "People who made this experience special",
    "summary": "The teammates, mentors, and fellow interns who shaped the experience.",
    "image": "imgs/moodys/slide-07.webp",
    "source": "moodys-intern-slides/moodys-slide-3.html",
    "transcript": "People who made this experience special\n\nMy manager Patrick Clarke, for not only his guidance, knowledge, and question answering abilities, but also his willingnes to share his love for tea with me.\n\nThe rest of the developer team, Jakir Hossain and Shuai Hao, for their careful guidance, helpful feedback, and advice that I will take with me even after this internship.\n\nThe whole Multimedia & Graphics Team, for welcoming me and including me in not only their projects, but also numerous meetings, lunches, and events!\n\nAnd of course the entire 2026 Summer Intern Group!"
  },
  {
    "title": "Thank you",
    "summary": "The closing slide from my final presentation.",
    "image": "imgs/moodys/slide-08.webp",
    "source": "moodys-intern-slides/moodys-slide-2.html",
    "transcript": "Thank you for your attention!"
  }
];
